volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - "local.env"
    ports:
      - "${PG_PORT}:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pg-prod:
     image: postgres:14-alpine3.17
     env_file:
      - "prod.env"
     ports:
        - "${PG_PORT}:5433"
     volumes:
        - postgres_volume:/var/lib/postgresql/data
        
  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    env_file:
      - "local.env"
  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod