name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/andrei-shkolnyi"
  IMAGE_NAME: "chat-server"
  CONTAINER_NAME: "chat-server-container"
jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --timeout=30m --config=./.golangci.pipeline.yaml

  build-and-test:
    runs-on: ubuntu-latest
    needs: linter
    steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.24.4'
            cache-dependency-path: go.sum

        - name: Build
          run: go build -o ./bin/ -v ./...

        - name: Test
          run: go test -v ./...

  
  build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Registry
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}

      - name: Build and push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME .
    
  deploy-image:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            #Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            # Login into Selectel Registry
            echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ env.REGISTRY }}

            # Stop running container
            docker stop $CONTAINER_NAME || true

            # Remove container
            docker rm $CONTAINER_NAME || true

            # Run a new container from a new image
            docker run -d -p 50054:50054 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME



  
